# Generated by Django 5.2 on 2025-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='categorie',
            field=models.CharField(choices=[('cuisine', 'Cuisine'), ('patisserie', 'Pâtisserie'), ('entreprenariat', 'Entreprenariat'), ('makeup', 'Makeup'), ('couture', 'Couture'), ('developpement personnel', 'Développement personnel'), ('informatique', 'Informatique'), ('reseau', 'Réseau'), ('gestion de projet', 'Gestion de projet')], max_length=50),
        ),
    ]
