# Generated by Django 5.2 on 2025-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_cours_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
