# Generated by Django 5.2 on 2025-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_cours_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='module',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
