# Generated by Django 5.2 on 2025-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_remove_module_quiz_alter_module_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
