# Generated by Django 5.2 on 2025-06-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_question_choix_quiz_question_quiz_reponseutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='titre',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(default='Question à définir'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.module'),
        ),
    ]
